openapi: 3.0.0
info:
  title: Node Leaning API
  version: 1.0.0
  description: swagger api documents authentication
servers:
  - url: http://localhost:3000
tags:
  - name: Authentication
    description: Authentication operations
paths:
  /Auth/Login:
    post:
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthLogin'
      responses:
        '200':
          description: Successful login
        '401':
          description: Unauthorized
  /Auth/Register:
    post:
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthRegister'
      responses:
        '201':
          description: User registered successfully
        '400':
          description: Bad request
  /Users:
    get:
      tags:
        - Users
      responses:
        '200':
          description: Users List
          content:
            application/json:
              schema:
                type: array
        '400':
          description: Bad request
  /Users/{id}:
    get:
      tags:
        - Users
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: number
          description: user id
      responses:
        '200':
          description: User information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: User not found
        '400':
          description: Bad request

components:
  schemas:
    AuthLogin:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
        password:
          type: string
    AuthRegister:
      type: object
      required:
        - username
        - email
        - password
        - address
      properties:
        username:
          type: string
        email:
          type: string
        password:
          type: string
        address:
          type: string
    User:
      type: object
      properties:
        id:
          type: number
